[General]
# Background Image Path
background=assets/images/background.jpeg

# High-Contrast Monochrome
accentColor=#D71921
textColor=#FFFFFF
use24HourClock=false

# Font settings
fontFamily=Ndot 57 Aligned
fontSize=14
