services:
  testapp:
    image: ${DOCKER_REGISTRY-}testapp
    build:
      context: .
      dockerfile: TestApp/Dockerfile
    ports:
      - "5000:80"  # Maps port 80 in container to 5000 on host
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=aspnet-TestApp-0c355292-4b50-465b-b1c6-c1295cd97694;User=sa;Password=Nhattruong@1024;Encrypt=True;TrustServerCertificate=True;
  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      SA_PASSWORD: "Nhattruong@1024"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  mssqldata:
