####################
### ENVIRONMENTS ###
####################

# env = XCURSOR_SIZE,11
# env = HYPRCURSOR_SIZE,24

# env = GDK_SCALE,1
# env = GDK_DPI_SCALE,1
# env = QT_SCALE_FACTOR,1.2
# #env = XCURSOR_SIZE,24

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = GDK_SCALE,1
env = GDK_DPI_SCALE,1

env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORMTHEME,qt5ct

exec-once = gsettings set org.gnome.desktop.interface font-name 'Inter 10'

env = ELECTRON_OZONE_PLATFORM_HINT,auto
